# 'ConnectionError' also exists in python
class ConnectionError_(Exception):
	pass
